In [37]:
import math
import numpy as np

In [38]:
beta = 1
A = [[(math.sqrt(2*math.cosh(beta))-math.sqrt(2*math.sinh(beta)))/2,(math.sqrt(2*math.cosh(beta))+math.sqrt(2*math.sinh(beta)))/2],\
     [(math.sqrt(2*math.cosh(beta))+math.sqrt(2*math.sinh(beta)))/2,(math.sqrt(2*math.cosh(beta))-math.sqrt(2*math.sinh(beta)))/2]]
print(A)

[[0.11182257238717896, 1.6449247827070268], [1.6449247827070268, 0.11182257238717896]]


In [39]:
B = np.zeros(shape=(2,2,2))
for i in range(2):
    for j in range(2):
        for k in range(2):
            for n in range(2):
                B[i][j][k] += A[n][i]*A[n][j]*A[n][k]
print(B)

[[[ 4.45219879  0.32313562]
  [ 0.32313562  0.32313562]]

 [[ 0.32313562  0.32313562]
  [ 0.32313562  4.45219879]]]


In [40]:
C = np.zeros(shape=(2,2,2,2,2))
for a in range(2):
    for b in range(2):
        for c in range(2):
            for d in range(2):
                for e in range(2):
                    for i in range(2):
                        for j in range(2):
                            for k in range(2):
                                for l in range(2):
                                    for m in range(2):
                                        C[a][b][c][d][e] += B[a][i][j]*B[b][j][k]*B[c][k][l]*B[d][l][m]*B[e][m][i]
print(C)

[[[[[ 1799.27701687   159.95048372]
    [  159.95048372    51.32212825]]

   [[  159.95048372    17.31761999]
    [   51.32212825    51.32212825]]]


  [[[  159.95048372    17.31761999]
    [   17.31761999    17.31761999]]

   [[   51.32212825    17.31761999]
    [   51.32212825   159.95048372]]]]



 [[[[  159.95048372    51.32212825]
    [   17.31761999    51.32212825]]

   [[   17.31761999    17.31761999]
    [   17.31761999   159.95048372]]]


  [[[   51.32212825    51.32212825]
    [   17.31761999   159.95048372]]

   [[   51.32212825   159.95048372]
    [  159.95048372  1799.27701687]]]]]


In [41]:
D = np.zeros(shape=(2,2,2,2,2,2,2,2,2,2))
for a in range(2):
    for b in range(2):
        for c in range(2):
            for d in range(2):
                for e in range(2):
                    for f in range(2):
                        for g in range(2):
                            for h in range(2):
                                for i in range(2):
                                    for j in range(2):
                                        for i0 in range(2):
                                            for i1 in range(2):
                                                for i2 in range(2):
                                                    for i3 in range(2):
                                                        for i4 in range(2):
                                                            for i5 in range(2):
                                                                for i6 in range(2):
                                                                    for i7 in range(2):
                                                                        for i8 in range(2):
                                                                            for i9 in range(2):
                                                                                    D[a][b][c][d][e][f][g][h][i][j] += C[i0][i1][i2][i3][i4]*C[i5][i0][i6][j][a]*C[i6][i1][i7][b][c]*C[i7][i2][i8][d][e]\
                                                                                    *C[i8][i3][i9][f][g]*C[i9][i4][i5][h][i]
print(D)

[[[[[[[[[[  3.68176788e+19   3.36841304e+18]
         [  3.36841304e+18   3.09050498e+17]]

        [[  3.36841304e+18   3.12106078e+17]
         [  1.36259919e+18   1.35705828e+17]]]


       [[[  3.36841304e+18   3.08246331e+17]
         [  3.12106078e+17   2.87577756e+16]]

        [[  3.09050498e+17   2.87577756e+16]
         [  1.35705828e+17   1.47116483e+16]]]]



      [[[[  3.36841304e+18   3.08278550e+17]
         [  3.30687731e+17   3.05963754e+16]]

        [[  3.12106078e+17   2.91665694e+16]
         [  1.76762687e+17   2.00017473e+16]]]


       [[[  1.36259919e+18   1.25305774e+17]
         [  1.76762687e+17   1.76408212e+16]]

        [[  1.35705828e+17   1.39444799e+16]
         [  1.92207246e+17   3.31856332e+16]]]]]




     [[[[[  3.36841304e+18   3.08398950e+17]
         [  3.08278550e+17   2.83487989e+16]]

        [[  3.08246331e+17   2.86438642e+16]
         [  1.25305774e+17   1.29665274e+16]]]


       [[[  3.12106078e+17   2.86438642e+16]
         [  2.91665

In [42]:
Z = 0
for a in range(2):
    for b in range(2):
        for c in range(2):
            for d in range(2):
                for e in range(2):
                    for f in range(2):
                        for g in range(2):
                            for h in range(2):
                                for i in range(2):
                                    for j in range(2):
                                        Z += D[a][b][c][d][e][f][g][h][i][j] * D[b][c][d][e][f][g][h][i][j][a]
print(Z)

2.95434242935e+39


In [43]:
math.log(Z)/60

1.5147349120787537

In [45]:
math.log(2)

0.6931471805599453